apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ketanpod
  name: ketanpod
spec:
  containers:
  - image: nginx
    name: ketanpod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
