apiVersion: v1
kind: Pod
metadata:
  name: kpod
  labels:
    adhoc: ketanpod
spec:
  containers:
  - image: nginx
    name: testpod
    ports:
      - name: port80
        containerPort: 80
      - name: port443
        containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: MyApp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9376
    - name: https
      protocol: TCP
      port: 443
      targetPort: 937
