apiVersion: v1
kind: Pod
metadata:
  name: adhocpod1
  labels:
    adhoc: ketanq2
spec:
  containers:
  - image: nginx
    name: testpod
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: Pod
  name: q2svcketan
spec:
  ports:
    - name: myport
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    run: hello
  type: NodePort

