apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ketansvc
  name: ketansvc
  namespace: ketan
spec:
  ports:
  - name: "80"
    nodePort: 31212
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ketanpod
  type: NodePort
status:
  loadBalancer: {}
