apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    x: test
spec:
  containers:
  - image: nginx
    name: testpod
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: Pod
  name: nginx-service
spec:
  ports:
    - name: myport
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    run: test
  type: NodePort
